### DISCUSSION TITLE
Site Settings dialog always scrolling to bottom of body

### DISCUSSION THREAD

**Discussion by coderdnewbie** [microsoft/fluentui-blazor#2468] [Q&A] [answered]
I am trying to implement the site settings dialog and it works fine apart from the body scroll always being activated. I am hoping someone else knows the solution to resolve this issue. I have tried the css from the demo site and it is also doing this behavior, but works when the demo site is run.

This is what the page looks like before I click the site settings button (the body has a scroll bar):

![Top_of_page](https://github.com/user-attachments/assets/2dfd9cd7-23e5-4385-ba2a-512f7d9772fd)

This is what it looks like when I press the site settings dialog. The body has scrolled to the bottom of the page (this is the unwanted behavior):

![Site_settings_selected](https://github.com/user-attachments/assets/44ae3aec-12b2-4d0d-9cf0-8c0824f10109)

This is what it looks like when I close the site settings dialog:

![Bottom_of_page](https://github.com/user-attachments/assets/a4fe1ffe-e7b8-47c6-9c44-9334d0856448)

I am now at the bottom of the page and have to manually scroll to the top.

What am I doing wrong?

Here is some of the css on my site:

@import '/_content/Microsoft.FluentUI.AspNetCore.Components/css/reboot.css';

body {
    --body-font: "Segoe UI Variable", "Segoe UI", sans-serif;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    margin: 0;
}

.navmenu-icon {
    display: none;
}

.main {
    min-height: calc(100dvh - 86px);
    color: var(--neutral-foreground-rest);
    align-items: stretch !important;
    background: var(--neutral-layer-1);
}

.body-content {
    align-self: stretch;
    height: unset !important;
    display: flex;
}

.content {
    padding: 0.5rem 1.5rem;
    align-self: stretch !important;
    width: 100dvw;    
}

.manage {
    width: 100dvw;
}

**Comment by dvoituron** [comment]
Did you tried to apply this body style: https://www.fluentui-blazor.net/DesignTheme
```css
body {
    margin: 0;
    padding: 0;
    height: 100vh;    👈
    font-family: var(--body-font);
    font-size:   var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: var(--font-weight);
    color:       var(--neutral-foreground-rest);
    background:  var(--neutral-fill-layer-rest);
}
```
