### DISCUSSION TITLE
Collpas NavMenuContent on small screen

### DISCUSSION THREAD

**Discussion by BartNetJS** [microsoft/fluentui-blazor#2682] [Q&A]
How can i collapse the NavMenuContent on small device's.
And also even hide the menu buttons
Is that possible?

**Comment by dvoituron** [comment]
You could define a `main-layout-navmenu` CSS for mobile views:
And use a similar method for buttons.

```css
@media(min-width: 960px) {
    .main-layout-navmenu {
        display: none;
    }
}
```
