### DISCUSSION TITLE
How to change css variables in dark mode?

### DISCUSSION THREAD

**Discussion by pmeems** [microsoft/fluentui-blazor#3017] [Q&A]
As mentioned in #3016  I'm trying another time to implement light-dark mode in my application.
I still don't understand how the Design Tokens work, I can't find any example. I'm wondering if anybody does understand the tokens 😁

Using CSS I got a long way. Using the newly added [light-dark()](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/light-dark) CSS function helped a lot. 

I now have my header, footer in the same background color in dark and light mode. I have my menu in the correct colors and the white background is switched to a dark gray when in dark mode.

I'm now struggling with the buttons. It seems I can't get them to use the correct color. In light mode it is OK, in dark mode it should use the same color.

Here's an example of my use of the light-dark function:

```css
html, * {
  font-family: var(--font-roboto);
  font-size: var(--type-ramp-base-font-size);
  line-height: var(--type-ramp-base-line-height);
  font-weight: 400;
  color: light-dark(var(--darkblue-color), whitesmoke);
}
body {
  background-color: light-dark(whitesmoke, rgb(51, 51, 51));
}
```

This is how I try to change the CSS variables:
```css
body[data-theme="dark"],
body[data-theme="system-dark"] {
  --accent-base-color: var(--orangered-color);
  --accent-fill-rest: #c2350b;
  --accent-fill-hover: #d13c0d;
  --accent-fill-active: #e4450e;
  --accent-fill-focus: #c2350b;
  --accent-foreground-rest: #831905;
  --accent-foreground-hover: #6d0f03;
  --accent-foreground-active: #bb320b;
  --accent-foreground-focus: #831905;
  --accent-stroke-control-rest: linear-gradient(#c84923 90%, #842407 100%);
  --accent-stroke-control-hover: linear-gradient(#d54e23 90%, #942b09 100%);
  --accent-stroke-control-active: #e65624;
  --accent-stroke-control-focus: linear-gradient(#c84923 90%, #842407 100%);
}
```

I can see the values have changed but further down in the 'constructed stylesheet' I see the variables are changed again, this time to the 'wrong' colors.

How can I set the colors of the buttons the way I want, which is basically don't change wether it is dark or light mode?
