### DISCUSSION TITLE
question: black border around a focused FluentListbox when is part of FluentPopover

### DISCUSSION THREAD

**Discussion by lnaie** [microsoft/fluentui-blazor#3500] [Q&A]
Hello,

I can't figure where out how to turn off this border when the FluentListbox  is part of a popover, within a form, and is focused. It looses the border when is not focused, I think it turns gray. 

![Image](https://github.com/user-attachments/assets/0d627c56-814b-4a18-b91f-6922b6755f78)

Thanks

**Comment by dvoituron** [comment]
This border is the default behavior for Accessibility.

You can probably use a CSS style like this, replacing `YourElement` with a proper CSS selector.

```css
YourElement:focus {
    border: none; /* Remove the border */
    outline: none; /* Remove the default outline */
}
```
