### DISCUSSION TITLE
[FluentTextArea] Turn off text wrapping?

### DISCUSSION THREAD

**Discussion by Stephen-Lamb** [microsoft/fluentui-blazor#3842] [Q&A] [answered]
Hi, it is possible to turn off text wrapping with the FluentTextArea control? According to [MDN ](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/textarea#wrap) there's a "wrap" attribute on the textarea control that can do this but I can't figure out how to do this with the FluentTextArea control. Can I do it using shadowRoot or something? Thanks.

**Comment by vnbaaij** [comment]
You could try to target the text area in the shadow dom indeed. No idea it it works, though.

**Reply by MarvinKlein1508** [reply, marked as answer]
Yes this can be achieved by CSS.

```css
fluent-text-area::part(control) {
    white-space: nowrap;
}
```

You can also use a class for this like this:
```css
fluent-text-area.nowrap::part(control) {
    white-space: nowrap;
}
```

And then in razor:
```razor
<FluentTextArea Class="nowrap" @bind-Value=value2 Label="With label:" />
```

@vnbaaij Stephen is right though there is an attribute called `wrap` which will only get applied to the `fluent-text-area` but not the actual `textarea` element itself. Is this something we should address or do we call it a day with the CSS approach?
