### DISCUSSION TITLE
I want to notify users when a field has an invalid value.

### DISCUSSION THREAD

**Discussion by dimohy** [microsoft/fluentui-blazor#546] [Q&A] [answered]
Hi there

Is there a way to validate input values to highlight focus and borders if they are incorrect?

I want to achieve a result similar to the effect below.

![image](https://github.com/microsoft/fluentui-blazor/assets/58620778/19c6e215-8c2e-4ad6-88ad-d23067d7785e)

**Comment by vnbaaij** [comment, marked as answer]
We will add this to the library for v3.0 final. As a workaround, add this somewhere in your CSS:
```css
.invalid::part(root) {
    outline: 1px solid var(--error);
}

.invalid[role='checkbox']::part(control) {
    outline: 1px solid var(--error);
}
```

Will give you this:
<img width="220" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/c8e379ef-20d2-4485-9036-66c1c176ea61">
