### DISCUSSION TITLE
Beginner information on layout element usage/guidelines?

### DISCUSSION THREAD

**Discussion by backcode-dev** [microsoft/fluentui-blazor#858] [Q&A] [answered]
I'm completely new to this framework so this question is from a beginner viewpoint. For context - I'm a long time C# dev with a bit of experience with ASP/MVC. Is there a document available that explains expected use of layout elements available to us?  I'm specifically thinking of equivalents to the Bootstrap system. There are pages about fluent UI on MS design but those are aspirational, not documentation :)

Is there an equivalent to "container" that items must be in? Is there an equivalent to "row" that items should be nested within?  FluentLayout doesn't have a width parameter so I assume it is supposed to be within elements like stack that do? I have rewritten the generated MainLayout.razor to use fluent elements, but I have not been able to get a working layout when using <FluentMainLayout ...> as the outer element. The <FluentMain> element does not work as expected when I replace the asp <main> element with it.  For example, FluentMain is not documented that I can see. The small samples on each element page often have "stock" elements (like <body> ) instead of using <fluentbody>, <header> instead of <fluentheader> etc. - so I do not have very many references.

I have a functional layout using the fluent grid, stack, and Layout elements but resizing, padding, and margins not always what I would expect without me adding some css - I'm assuming that I have nested elements improperly. Also - looking forward to the updated templates mentioned in github issues!

Thanks!

**Comment by vnbaaij** [comment, marked as answer]
Hi,

There is no document available like that. As opposed to Bootstrap, we do not prescribe what elements you need to realize a layout. We just provide some of the building blocks to help you. I think the demo site describes all of these well enough. Specifically https://www.fluentui-blazor.net/Layout shows a number of them working together.

If things are unclear, there is always the source of the components themselves, but also the source of the the demo site is available in the repo.

I think some examples have gone missing from your post

We kind of assume you to know css and html to make a layout look, act and behave as you want. We don't aim to cater every possible scenario with the components.

Yes, we (main maintainers) work for Microsoft and yes we implement Fluent in these Blazor components, but we are not an integral part of the Fluent team in Microsoft. Not everything they publish pertains to our library per se.

Hope this helps!

**Reply by backcode-dev** [reply]
Ok - that is definitely understandable. I'm not a webdev by trade so I'm not always up to speed ;) I'm used to libs having some (or lots) of undercover "magic".  As for the samples - the github editor ate everything I had in angle brackets - but that's moot now since your answer explains what I needed.  Thanks for the patient help!

**Comment by mguinness** [comment]
There's a good post [Getting started with Blazor and FluentUI](https://www.bytefish.de/blog/blazor_fluentui_container_grid.html) that is helpful.  It covers how to do responsive layouts which I think a lot of people coming from Bootstrap would want.

I'm looking to replicate [Navbar](https://getbootstrap.com/docs/5.2/components/navbar/) in Bootstrap, but [NavMenu](https://www.fluentui-blazor.net/NavMenu) looks to be vertical only.  I'm assuming I could use [Menu](https://www.fluentui-blazor.net/Menu) instead?

**Reply by vnbaaij** [reply]
It is a good post you link to, but it does not mention that we also have a [FluentGrid] (https://www.fluentui-blazor.net/Grid) component out-of-the-box.

For the NavBar, yes you can use the Menu component. Probably/maybe combined with the Toolbar

**Reply by mguinness** [reply]
> It is a good post you link to, but it does not mention that we also have a [FluentGrid](https://www.fluentui-blazor.net/Grid) component out-of-the-box.

It looks like the author of that post also discovered [FluentGrid](https://www.bytefish.de/blog/blazor_fluentui_and_odata.html#stringfilter) in a later post.

How would I go about recreating the old template behavior on Bootstrap where the nav menu is hidden on small screens by default with a hamburger menu to expand and display?

![Screenshot 2023-11-27 164652](https://github.com/microsoft/fluentui-blazor/assets/14002844/1b98ed03-4847-4909-86bc-6d01d47001ce)

Any guidance you can provide would be appreciated.

```html
<FluentLayout Style="height:100vh; background-color: var(--neutral-layer-1); color: var(--neutral-foreground-rest)">
    @* Header *@
    <FluentHeader>
        <div style="width: 100%">
            .NET Conf 2023
            <span style="float: right; cursor: pointer" class="hidden-sm hidden-md hidden-lg hidden-xl hidden-xxl"
                @onclick="@(() => Hidden ^= true)">☰</span>
        </div>
    </FluentHeader>

    <FluentBodyContent>

        <FluentGrid Spacing="0">
            <FluentGridItem xs="12" sm="3" Class="@(Hidden ? "hidden-xs" : null)">
                @* Left Menu *@
                <FluentNavMenu Title="Navigation menu">
                    <FluentNavLink Icon="@(new Icons.Regular.Size20.Home())"
                                   Href="/" Match="NavLinkMatch.All">Home</FluentNavLink>
                    <FluentNavLink Icon="@(new Icons.Regular.Size20.AddSquare())"
                                   Href="/Counter">Counter</FluentNavLink>
                    <FluentNavLink Icon="@(new Icons.Regular.Size20.WeatherRainShowersDay())"
                                   Href="/Weather">Weather</FluentNavLink>
                </FluentNavMenu>
            </FluentGridItem>
            <FluentGridItem xs="12" sm="9">
                @* Content *@
                <div class="main-content">
                    @Body
                </div>
            </FluentGridItem>
        </FluentGrid>

    </FluentBodyContent>

    @* Footer *@
    <FluentFooter>
        Microsoft 2023
    </FluentFooter>

</FluentLayout>

@code
{
    bool Hidden = true;
}
```

**Reply by vnbaaij** [reply]
We have something similar already included in the demo site. We actually show the menu expanded on mobile and hen collapse it once a user navigates to a page. All the code can be found under the `examples` folder in the repo. It involves using a hidden checkbox element and the hiding/showing is done with css only (see https://github.com/microsoft/fluentui-blazor/blob/5a991ab5f0e7dd452e377a8eff07f9a2b0cab9ac/examples/Demo/Shared/wwwroot/css/site.css#L296)

![image](https://github.com/microsoft/fluentui-blazor/assets/1761079/119edcee-e52a-44fa-9203-7f9354e861a0)

**Reply by mguinness** [reply]
I'll take a further look at that demo site although it doesn't appear to use `FluentGrid`? 

When using `FluentGrid` how do you hide `FluentGridItem` when screen size < 600px?

In Bootstrap [documentation](https://getbootstrap.com/docs/5.2/utilities/display/#hiding-elements) you would use class `d-none` to hide elements repsonsively.

**Reply by vnbaaij** [reply]
We don't have anything for that out of the box. 

It is not our goal to be a complete UI framework, like Bootstrap. We provide a set of components that work well together and implement the Fluent Design language but I'm not foreseeing any big changes or additions to that at the moment.

**Reply by mguinness** [reply]
That's unfortunate, I imagine others will also be needing a solution OOB for this.  Below is my attempt at getting this to work. 

```CSS
@media (max-width: 599px) {
    .hidden-xs {
        display: none !important;
    }
}

@media (min-width: 600px) and (max-width: 959px) {
    .hidden-sm {
        display: none !important;
    }
}

@media (min-width: 960px) and (max-width: 1279px) {
    .hidden-md {
        display: none !important;
    }
}

@media (min-width: 1280px) and (max-width: 1919px) {
    .hidden-lg {
        display: none !important;
    }
}

@media (min-width: 1920px) and (max-width: 2559px) {
    .hidden-xl {
        display: none !important;
    }
}

@media (min-width: 2560px) {
    .hidden-xxl {
        display: none !important;
    }
}
```

|  | **X Small** <600px | **Small** ≥600px | **Medium** ≥960px | **Large** ≥1280px | **X Large** ≥1920px | **XX Large** ≥2560px |
|---|:---:|:---:|:---:|:---:|:---:|:---:|
| `.hidden-xs` | :white_check_mark: | :x: | :x: | :x: | :x: | :x: |
| `.hidden-sm` | :x: | :white_check_mark: | :x: | :x: | :x: | :x: |
| `.hidden-md` | :x: | :x: | :white_check_mark: | :x: | :x: | :x: |
| `.hidden-lg` | :x: | :x: | :x: | :white_check_mark: | :x: | :x: |
| `.hidden-xl` | :x: | :x: | :x: | :x: | :white_check_mark: | :x: |
| `.hidden-xxl` | :x: | :x: | :x: | :x: | :x: | :white_check_mark: |

**Reply by vnbaaij** [reply]
This is great! Think we can put this in the Grid's css file.
Looking at that file, we only have medaiqueries there for `min-width` values. Why do you include the `max-width` values? Are the needed?

I'm not a CSS expert, so maybe a dumb question...

**Reply by mguinness** [reply]
If you'd prefer ranges to sizes then you could use the alternate styles below.  That way you could replace `hidden-sm hidden-md hidden-lg hidden-xl hidden-xxl` with `hidden-sm-up` and `hidden-xs` with `hidden-xs-down` that was used in the markup shown in [comment](https://github.com/microsoft/fluentui-blazor/discussions/858#discussioncomment-7686827) above.

```CSS
.hidden-xs-up {
  display: none !important;
}

@media (max-width: 599px) {
  .hidden-xs-down {
    display: none !important;
  }
}

@media (min-width: 600px) {
  .hidden-sm-up {
    display: none !important;
  }
}

@media (max-width: 959px) {
  .hidden-sm-down {
    display: none !important;
  }
}

@media (min-width: 960px) {
  .hidden-md-up {
    display: none !important;
  }
}

@media (max-width: 1279px) {
  .hidden-md-down {
    display: none !important;
  }
}

@media (min-width: 1280px) {
  .hidden-lg-up {
    display: none !important;
  }
}

@media (max-width: 1919px) {
  .hidden-lg-down {
    display: none !important;
  }
}

@media (min-width: 1920px) {
  .hidden-xl-up {
    display: none !important;
  }
}

@media (max-width: 2559px) {
  .hidden-xl-down {
    display: none !important;
  }
}

@media (min-width: 2560px) {
  .hidden-xxl-up {
    display: none !important;
  }
}

.hidden-xxl-down {
  display: none !important;
}
```
