### ISSUE TITLE
feat: add stroke width property to FluentProgressRing

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#1113]
# 🙋 Feature Request

`FluentProgressRing` doesn't have an easy way to change the stroke width, i.e. the thickness of the circle outline. When a small progress ring is displayed the hard coded width is too small.

CSS alone can't change the ring width appearance because the SVG position of the outline also needs to change based on the line width.

## 🤔 Expected Behavior

There is a way to change the `FluentProgressRing` stroke width.

## 😯 Current Behavior

No customization.

## 💁 Possible Solution

A parameter on `FluentProgressRing`. I'm not sure what the unit would be because the width would be scaled with the ring.

## 🔦 Context

Displaying a small ring in a grid at https://github.com/dotnet/aspire/pull/1387

**Comment by JamesNK** [comment]
We were able to do this with a CSS solution: https://github.com/dotnet/aspire/pull/1387#issuecomment-1855296556

**Comment by dvoituron** [comment]
Thanks. But I find interesting to add two new attributes in FluentProgressRing: Color and StrokeWidth.

**Comment by dvoituron** [comment]
Your solution proposed in Aspire is correct, but the `Value` seems not correct for the result. Ex. `Value=50%`.
- Before (without CSS)
![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/8e4405ae-4b82-490b-8fee-c87cf3b3946a)
- After (with CSS)
![image](https://github.com/microsoft/fluentui-blazor/assets/8350694/109d62fb-9216-4748-9aa6-f77983b6bbfe)

```css
::deep fluent-progress-ring::part(background) {
    stroke: var(--neutral-fill-input-alt-active);
    stroke-width: 4px;
    r: 6px;
}

::deep fluent-progress-ring::part(determinate) {
    stroke-width: 4px;
    r: 6px;
}
```
