### ISSUE TITLE
redundant padding in FluentMessageBarProvider component

### ISSUE THREAD

**Issue by c0nd3v** [microsoft/fluentui-blazor#1312]
#1017 is not fixed. The recommended solution was to put FluentMessageBarProvider at the end of MainLayout. All that does is move the redundant padding to the bottom of the page. The only way to fix this is by doing:

```html
<FluentMessageBarProvider style="padding: 0px" />
```
or
```css
.fluent-messagebar-provider {
    /* workaround for https://github.com/microsoft/fluentui-blazor/issues/1017 */
    padding-bottom: unset !important;
}
```

But why is this necessary? Please fix it
