### ISSUE TITLE
Safe Area Support for Toast, Panel and etc..

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/fluentui-blazor#1371]
I'm not sure, if this is feature request or this can be done with css or Js today, But how to make the Toast, Panel and etc to respect the safe area that set for selected devices like iPhones through adding safe area construct in css like below

```css
.status-bar-safe-area {
    display: none;
}

@supports (-webkit-touch-callout: none) {
    .status-bar-safe-area {
        display: flex;
        position: sticky;
        top: 0;
        height: env(safe-area-inset-top);
        background-color: var(--neutral-layer-1);
        width: 100%;
        z-index: 1;
    }

    .flex-column, .navbar-brand {
        padding-left: env(safe-area-inset-left);
    }

    #body-content {
        padding-bottom: 35px;
    }
}
```

Safe area div in index.html
```html

<body>
    <div class="status-bar-safe-area"></div>
</body>

```
