### ISSUE TITLE
There is a lot of css in the style of single card components, if i @for(... ){ <card></card>},   It and its style will be repeated many times，

### ISSUE THREAD

**Issue by withyzu** [microsoft/fluentui-blazor#1592]
## There is a lot of css in the style of single card components, if i @for(... ){ <card></card>},   It and its style will be repeated many times，So What can I do， and Shadow make me crazy， i hope this ui-library will be perfect ！！！😥😥😥

---

![Snipaste_2024-02-27_23-00-18](https://github.com/microsoft/fluentui-blazor/assets/64072282/a7405289-2b8e-4337-a896-a6e7a381b6ed)
![Snipaste_2024-02-27_23-00-40](https://github.com/microsoft/fluentui-blazor/assets/64072282/4a8c8742-c4dd-426d-b4a6-b3e707a7a4b2)
![Snipaste_2024-02-27_23-00-49](https://github.com/microsoft/fluentui-blazor/assets/64072282/93d56dc5-4eac-43de-b20a-d21f11308b07)

**Comment by withyzu** [comment]
Or maybe I'm using it incorrectly. It's not a bug😫

**Comment by vnbaaij** [comment]
This is just how the underlying web component works atm. Nothing we can do/change about that.

Normally, when using the components, ou do not need to do anything with the shadow dom. Just accept that it is there and let it do its job.

**Comment by dvoituron** [comment]
Like Vincent said, it's by design. If you want only to display the same card effect, you can apply a style like this:

```css
    .card-style {
        display: block;
        padding: calc(var(--design-unit)* 5px);
        background: var(--fill-color);
        color: var(--neutral-foreground-rest);
        border: calc(var(--stroke-width)* 1px) solid var(--neutral-stroke-layer-rest);
        border-radius: calc(var(--layer-corner-radius)* 1px);
        box-shadow: var(--elevation-shadow-card-rest);
    }
```

@vnbaaij  We could add a note in the documentation about that.
