### ISSUE TITLE
Wizard Separator Broken

### ISSUE THREAD

**Issue by achmstein** [microsoft/fluentui-blazor#1765]
The Wizard separator is broken for Top position in RTL for last step

![Screenshot 2024-03-30 011909](https://github.com/microsoft/fluentui-blazor/assets/15241305/675e9879-5536-42ea-814d-508f09a88adb)

**Comment by vnbaaij** [comment]
Fix is pushed. Will be in next release.

**Comment by achmstein** [comment]
Broken in the right position

![Annotation 2024-05-08 081050](https://github.com/microsoft/fluentui-blazor/assets/15241305/f7099f38-7bad-481d-baac-407f6a41cf07)

**Comment by dvoituron** [comment]
@achmstein 
We will correct this problem in the next version. In the meantime, you can add this CSS to solve the problem.

```css
[dir="rtl"] .fluent-wizard[position="left"] > ol > li:not(:last-child):after {
    left: revert;
    transform: translateX(calc(var(--fluent-wizard-circle-size) / -2));
}
```
