### ISSUE TITLE
fix: [Fluent Select] in [Mobile]

### ISSUE THREAD

**Issue by sardar97** [microsoft/fluentui-blazor#1814]
when i want use fluent selects
on mobile it has this problem as i showed in the picture. it is doesn't show the combobox correctly it is like showing behind something!!.
![image](https://github.com/microsoft/fluentui-blazor/assets/96167344/7717a27f-753b-4795-91fd-a1a47ac8e627)

**Comment by dvoituron** [comment]
It seems that the `height` of your Container (`body`?) is not 100%, given the scroll bar on the right.
Is this correct?
Can you increase the height?

**Comment by dvoituron** [comment]
For example, to solve this issue in your project, you can update the `height` of `body-content` to `100vh` or another computed value.

```css
.body-content {
    align-self: stretch;
    height: 100vh !important;   /* 👈 HERE */
    display: flex;
}
```
