### ISSUE TITLE
Allow to hide any item on different breakpoints

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#1842]
# 🙋 Feature Request

The Grid component allows you to hide certain columns on different breakpoints.
https://www.fluentui-blazor.net/Grid

For example:
```asp 
<FluentGridItem xs="12" sm="6" HiddenWhen="GridItemHidden.SmAndDown">
        <div class="card">
            xs="12" sm="6" Hidden="SmAndDown"
        </div>
 </FluentGridItem>
```

When you take a look on the CSS here you can see that this rules only apply to divs within `.fluent-grid`

```css
/* Hidden */

@media (max-width: 599.98px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="xs"] {
        display: none;
    }
}

@media (min-width: 600px) and (max-width: 959.98px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="sm"] {
        display: none;
    }
}

@media (min-width: 960px) and (max-width: 1279.98px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="md"] {
        display: none;
    }
}

@media (min-width: 1280px) and (max-width: 1919.98px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="lg"] {
        display: none;
    }
}

@media (min-width: 1920px) and (max-width: 2559.98px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="xl"] {
        display: none;
    }
}

@media (min-width: 2560px) {
    .fluent-grid[b-j6ju2n507t]  > div[hidden-when~="xxl"] {
        display: none;
    }
}
```

However this feature is useful in any area within an app and it should not be tied to the `fluent-grid` alone. I suggest changing this lines to simply:

```css
/* Hidden */

@media (max-width: 599.98px) {
    [hidden-when~="xs"] {
        display: none;
    }
}

@media (min-width: 600px) and (max-width: 959.98px) {
    [hidden-when~="sm"] {
        display: none;
    }
}

@media (min-width: 960px) and (max-width: 1279.98px) {
    [hidden-when~="md"] {
        display: none;
    }
}

@media (min-width: 1280px) and (max-width: 1919.98px) {
    [hidden-when~="lg"] {
        display: none;
    }
}

@media (min-width: 1920px) and (max-width: 2559.98px) {
    [hidden-when~="xl"] {
        display: none;
    }
}

@media (min-width: 2560px) {
    [hidden-when~="xxl"] {
        display: none;
    }
}
```

When doing this we can apply it to each element in our app like this:
```asp
<div class="list-item" hidden-when="xs sm">
    <label>Id</label>
    <span>@item.UserId</span>
</div>
```

This would also align with Bootstrap's feature to hide items using their display utilities.
https://getbootstrap.com/docs/5.3/utilities/display/#hiding-elements
