### ISSUE TITLE
feat: Provide a row hover effect on DataGrid using same style of sortable column header hover effect

### ISSUE THREAD

**Issue by StephenOTT** [microsoft/fluentui-blazor#1933]
# 🙋 Feature Request

Currently row hover has to be done manually per: https://github.com/microsoft/fluentui-blazor/discussions/1745#discussioncomment-8927074

## 🤔 Expected Behavior

Ability to activate a row hover effect in the same style at the hover effect shown on sortable column headers

## 😯 Current Behavior

No hover effect is shown

## 💁 Possible Solution

Configurable option on data grid to activate hover effect on row

## 🔦 Context

When user is hovering over a row we want to make it clear which row they are hovering on.

This is especially important when using the onRowFocus callback to allow users to select rows.

Current workaround is to implement rowClass and css such as:

css isolation example:

```css
::deep fluent-data-grid-row.myrowclass:hover {
    cursor: pointer;
    background-color: #c0c0c01f;
}
```

app.css example:

```css
fluent-data-grid-row.myrowclass:hover {
    cursor: pointer;
    background-color: #c0c0c01f;
}
```
