### ISSUE TITLE
fix: initial ActiveIndicator in FluentTabs

### ISSUE THREAD

**Issue by SteveSandersonMS** [microsoft/fluentui-blazor#2095]
# 🐛 Bug Report

With `FluentTabs`, if the initially active tab is not the first one, then it performs a weird animation on page load.

## 💻 Repro or Code Sample

```razor
    <FluentTabs Style="width: 100%" ActiveTabId="closed">
        <FluentTab Id="open" Label="Open" />
        <FluentTab Id="closed" Label="Closed" />
    </FluentTabs>
```

## 🤔 Expected Behavior

On page load, the "closed" tab should be highlighted as active. No animation should occur.

## 😯 Current Behavior

On page load, the "open" tab is highlighted as active, followed by an animation where "closed" becomes active.

![open-closed-bug](https://github.com/microsoft/fluentui-blazor/assets/1101362/5d74c2e3-743b-4bc8-98ca-4f844fe8343d)

It's just a bit jarring.

## 🔦 Context

Just trying to set the initial tab based on the URL.

## 🌍 Your Environment

FluentUI 4.7.1, Chromium browser

**Comment by dvoituron** [comment]
This animation comes from the web components we use in the background.
We have no control over this functionality.

For example, your code generates the following HTML code (simplified) which gives the same result.

```html
<fluent-tabs activeid="closed">
    <fluent-tab id="open">Open</fluent-tab>
    <fluent-tab id="closed">Closed</fluent-tab>

    <fluent-tab-panel>Content Open</fluent-tab-panel>
    <fluent-tab-panel>Content Closed</fluent-tab-panel>
</fluent-tabs>
```

**Comment by dvoituron** [comment]
I found a workaround to solve this issue:

1. Remove the default indicator using `ShowActiveIndicator="false"`.
2. Add this CSS to your `style.css` file to simulate the same indicator, without the animation.
    ```css
    fluent-tab[aria-selected="true"]::after {
        content: "";
        position: absolute;
        height: 3px;
        background: var(--accent-fill-rest);
        width: 20px;
        bottom: 4px;
    }
    ```
