### ISSUE TITLE
fix: FluentDataGrid with ResizableColumns allows sortable column resize handle to be covered by adjacent column header

### ISSUE THREAD

**Issue by kjkrum** [microsoft/fluentui-blazor#2167]
Create a `FluentDataGrid` with `ResizableColumns="true"` and at least one `PropertyColumn` with any other type of column to its right. Grab the resize handle to the right of the `PropertyColumn` and drag it left as far as it will go.

Problem: The header of the column to the right of the `PropertyColumn` covers the resize handle you are currently holding. If you release the mouse button you can never interact with that resize handle again.

This does not occur when dragging the resize handle to the right of a `TemplateColumn`.

**Comment by vnbaaij** [comment]
A fix for this will be in the next release. See #2059.

Also, if resizing ever gets messed up oy you just want a reset without reloading the page, shift+r key combo will reset to original layout and column sizes.

**Comment by kjkrum** [comment]
@vnbaaij I do not believe this is a duplicate. The fix for the similar issue was just CSS, so I copied the change from [c23f893](https://github.com/microsoft/fluentui-blazor/commit/c23f89368954985659ee00336782475ec9b5977c) into my app.css. I also added `background-color: red` to confirm that my changed CSS was matching the correct elements, which it was.

```CSS
.col-width-draghandle {
    height: auto;
    width: calc(var(--design-unit) * 1px + 2px);
    right: calc(var(--col-gap)/2 - 0.5rem);
    border-top: none;
    border-left: calc(var(--stroke-width) * 1px) solid var(--neutral-stroke-divider-rest);
    cursor: col-resize;
    position: sticky;
    background-color: red;
}
```
This does not solve the problem specifically affecting `PropertyColumn`. I'll write a SSCCE.
