### ISSUE TITLE
feat: Add BarHandle parameter to FluentMultiSplitter

### ISSUE THREAD

**Issue by emetrix** [microsoft/fluentui-blazor#2219]
# 🙋 Feature Request

Can you please consider a BarHandle parameter like in FluentSplitter for FluentMultiSplitter, too ?
I'n my opinion this would be a useful addition.

## 🤔 Expected Behavior

The parameter should enable/disable the display of the bar handle in the resize bar.

## 😯 Current Behavior

The bar handle is always visible in FluentMultiSplitter

**Comment by dvoituron** [comment]
What is missing in the CSS variables to configure that?

```css
    .fluent-multi-splitter {
        /* Resize Icon colors */
        --fluent-multi-splitter-color: var(--neutral-stroke-strong-rest);
        --fluent-multi-splitter-color-active: var(--neutral-stroke-strong-hover);

        /* Bar colors */
        --fluent-multi-splitter-background-color: var(--neutral-stroke-rest);
        --fluent-multi-splitter-background-color-active: var(--neutral-stroke-hover);
        --fluent-multi-splitter-hover-opacity: 0.8;

        /* Bar size */
        --fluent-multi-splitter-bar-size: 8px;
    }
```
