### ISSUE TITLE
FluentMenu (placed on the end of page) - Page content is resizing each time menu is opening

### ISSUE THREAD

**Issue by gryzorr** [microsoft/fluentui-blazor#2379]
# 🐛 Bug Report

When FluentMenu is place on right side of the page then content is resizing causing scrollbars to show and hide.

## 💻 Repro or Code Sample

Nothing special in code, see video.

## 🤔 Expected Behavior

Openned menu without page flickering.

## 😯 Current Behavior

Page flickering because of scrollbars showing/disappearing.

## 💁 Possible Solution

It would be nice have the same solution like in FluentProfileMenu (there was similar problem).

## 🔦 Context

Minor problem but nice to have.

## 🌍 Your Environment
* OS & Device: Windows
* Browser: Microsoft Edge, Google Chrome
* .NET and Fluent UI Blazor library Version: 4.9.1

https://github.com/user-attachments/assets/0a135327-2103-4fe2-88d2-d6b584d1b25c

**Comment by dvoituron** [comment]
Without a code example to reproduce this problem, we can't do anything.
Can you provide us with such an example?

Have you configured your HTML `body' style as described in the documentation: https://www.fluentui-blazor.net/DesignTheme

```css
body {
    margin: 0;
    padding: 0;
    height: 100vh;   👈
    font-family: var(--body-font);
    font-size:   var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: var(--font-weight);
    color:       var(--neutral-foreground-rest);
    background:  var(--neutral-fill-layer-rest);
}
```
