### ISSUE TITLE
fix: Accordion in dark mode

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#2444]
# 🐛 Bug Report
The accordion is very hard to see in dark mode:
![grafik](https://github.com/user-attachments/assets/3d30dc33-e0c6-4ea3-9b57-b3c7c199d0cd)

## 💁 Possible Solution

I've overritten the default styling like this:
```css
fluent-accordion-item {
	background-color: var(--neutral-fill-stealth-active-on-neutral-fill-layer-rest) !important;
}
```

This makes the accordion stand-out like this:
![grafik](https://github.com/user-attachments/assets/3d78c73a-9177-4328-9b56-9322d42920af)

## 🌍 Your Environment

Firefox Developer Edition latest version & Microsoft Edge latest version
