### ISSUE TITLE
fix: Weird scrolling in FluentDialogs

### ISSUE THREAD

**Issue by MarvinKlein1508** [microsoft/fluentui-blazor#3060]
# 🐛 Bug Report

I'm using both `bootstrap-grid.min.css` and `bootstrap-utilities.min.css` in my project. In addtion I've added the CSS to display bootstrap tables in my project. When I display a large table now within a `FluentDialog` (which causes scrolling) I'll get this weird scrolling behaviour where it first scrolls within just a little bit and then starting to scroll normally. Whenever I reach the top or bottom again, the same behaviour reoccurs. I've tried to catch it in a video for you.

https://github.com/user-attachments/assets/7aac9088-ae74-4f10-9914-0326667b4000

## 💻 Repro or Code Sample

I've created a small sample repo which can be found here: https://github.com/MarvinKlein1508/FluentUI-Scroll-Issue

## 🤔 Expected Behavior

I expect the content in the FluentDialog to be normally scrollable.

## 😯 Current Behavior

It only scrolls for a few pixels and then gets stuck until you start to scroll much harder.

## 🔦 Context

I've noticed the same behaviour a couple of times already also when using Fluent components like FluentGrid or FluentStack. This is also the reason why I've switched back to the bootstrap grid.

## 🌍 Your Environment

This seems to be a Firefox specific issue. It works fine for me in both Chrome and Edge

EDIT: It also works fine in Safari for me.

**Comment by dvoituron** [comment]
I think you need to fix the height of the dialog. For example with a `--table-responsive-height` CSS variable.

1. Updating your App.css file
    ```css
    body {
       --table-responsive-height: calc(100vh - 100px);
    }

    .table-responsive {
       height: calc(var(--table-responsive-height) - 200px);
       overflow-x: auto;
       -webkit-overflow-scrolling: touch;
    }
    ```

2.  Setting the Height property in your Home.razor file
    ```csharp
    DialogParameters parameters = new()
       {
           Height = "var(--table-responsive-height)",
           ...
       }
    ```

**Comment by MarvinKlein1508** [comment]
@dvoituron this seem to work. However this is not an optimal solution because it will always display all tables with this class with 100vh. It depends from customer to customer. With this approach all of my responsive tables would have 100vh of height.

In Bootstrap it ain't an issue either. See https://getbootstrap.com/docs/5.3/components/modal/#scrolling-long-content

I really want to have the height of the table set to auto. Isn't there any way to fix this for the dialog itself with some sort of CSS adjustment?

**Comment by dvoituron** [comment]
Of course, you need to adapt this sample with your project. For example, to apply the style only if it is used in a `fluent-dialog` (or using another CSS if you prefer).

```css
.table-responsive {
    -webkit-overflow-scrolling: touch;
    height: calc(var(--table-responsive-height) - 200px);
}

fluent-dialog .table-responsive {
    overflow-x: auto;
}
```
