### ISSUE TITLE
fix: Multiple = true in FluentListBox does not render multiple selections

### ISSUE THREAD

**Issue by thebarrettlo** [microsoft/fluentui-blazor#3140]
# 🐛 Bug Report

In the `FluentListBox` component when using `Multiple=true`, the selected options are correctly bound but the options are not rendered as being selected.

## 💻 Repro or Code Sample

In the `ListboxDefault.razor` demo site file, the code updated to below reflects this bug.

```csharp
<FluentListbox TOption="Person"
               Label="Select a person"
               Items="@Data.People"
               Id="people-listbox"
               Height="150px"
               OptionValue="@(p => p.PersonId.ToString())"
               OptionText="@(p => p.LastName + ", " + p.FirstName)"
               @bind-SelectedOptions="@SelectedItems"
               Multiple />

<p>
    Selected items: @(SelectedItems == null ? null : string.Join(", ", SelectedItems.Select(p => p.FirstName)))
</p>

@code
{
    IEnumerable<Person>? SelectedItems;
}
```

## 🤔 Expected Behavior

All currently selected items render a marker beside them indicating they're selected, as seen in `FluentSelect` when `Multiple=true`.

## 😯 Current Behavior

Only the last selected item has a marker beside it.

![Image](https://github.com/user-attachments/assets/e1f0e153-191f-42f7-bb0a-5069a45f41f9)

## 🔦 Context

Trying to use a list box to render values of an enum and allow the user to select multiple values.

## 🌍 Your Environment

* OS & Device: Windows 11 on virtual dev box
* Browser: Microsoft Edge
* .NET 9 and Fluent UI Blazor library Version 4.11.0

**Comment by vnbaaij** [comment]
Hi,

Listbox web component was to get multiple someday (see https://github.com/microsoft/fast/issues/4190) but it never got implemented correctly. With the v2 web components not being updated anymore, we are not going to get this on our side either.

Currently it only works for `FluentSelect` and as it then always displays expanded anyway, that kind of gives you a Listbox anyway

**Comment by vnbaaij** [comment]
PS I'll update the source comment to make clear it only works for select.

**Comment by jasonshave** [comment]
@vnbaaij  Any suggestions on how to make sure components below a FluentSelect appear below the list? I have this same issue but can't seem to ensure that something like a label, text box, or something else isn't lost behind the list. Since it's an 'expanded' list when multiple=true, it hides things behind it.

**Comment by jasonshave** [comment]
Unfortunately that didn't work. I tried a custom component-level css among a ton of other settings. It appears the underlying HTML it renders is a <div class="listbox"> which uses custom styling to override anything else. If I use F12 and set that <div> to use "position: static", it works, but I can't seem to impart that setting from the 'outside' via .css or a "style=" property.

**Comment by thebarrettlo** [comment]
@jasonshave Not a precise solution to the odd expanded positioning behavior with the select component when `Multiple=true`, but a few ideas/info:

- Scoped CSS (.razor.css files), if that's what you're using for "component-level CSS", [will only work for HTML elements written in the .razor file](https://learn.microsoft.com/en-us/aspnet/core/blazor/components/css-isolation?view=aspnetcore-9.0#:~:text=Scoped%20CSS%20only%20applies%20to%20HTML%20elements%20and%20not%20to%20Razor%20components%20or%20Tag%20Helpers%2C%20including%20elements%20with%20a%20Tag%20Helper%20applied%2C%20such%20as%20%3Cinput%20asp%2Dfor%3D%22...%22%20/%3E.), not even HTML elements generated by a nested component
- The `<div class="listbox" part="listbox" ...>` is within the `<fluent-select>`'s [`#shadow-root`](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM), so in order to get styles to apply to it (e.g., from your site.css), you can use the [`::part()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)
   - For example:
      ```css
      fluent-select::part(listbox) {
          ...
      }
      ```
- For my use case, I've "remade" the `FluentListBox` component for multiple selections by doing the following:

```razor
@* MyListboxComponent.razor *@

<div class="multiple-select-box">
    <FluentSelect Items=@NameValuePairs.Values
                  Multiple=true
                  OptionValue=@(...)
                  OptionText=@(...)
                  SelectedOptions=@CurrentValue
                  SelectedOptionsChanged=@HandleValueChanged />
</div>
```

```css
/* MyListboxComponent.razor.css */
.multiple-select-box {
    overflow-y: auto;
    border: calc(var(--stroke-width)* 1px) solid var(--neutral-stroke-rest); /* copied from the Fluent listbox component */
    border-radius: calc(var(--control-corner-radius)* 1px); /* copied from the Fluent listbox component */
    height: 150px;
    width: 100%;
}
```

```css
/* site.css */
.multiple-select-box fluent-select::part(listbox) {
    border-radius: unset; /* Remove rounded corners of multi-select component within container */
    box-shadow: unset;
}
```

Which ends up looking like this:

![Image](https://github.com/user-attachments/assets/639904dc-07d7-4692-999c-4f8798a86dfd)
