### ISSUE TITLE
fix: Grayed out selected text when there is a FluentSelect with placeholder

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#3940]
# 🐛 Bug Report

There is an issue when a FluentSelect has a place holder and is in a dialog. The text of the select is still grayed out color of the placeholder text after selecting a value.

For example, the default example at https://www.fluentui-blazor.net/Select has darker text when the select has a place holder and white text when a value is selected.

I think it is broken in my app because the select is in a dialog

## 💻 Repro or Code Sample

![Image](https://github.com/user-attachments/assets/fec48c1e-6774-4557-9e53-657219c44831)

## 🤔 Expected Behavior

Select text shouldn't be grayed out after a non-placeholder 

value is selected.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by MarvinKlein1508** [comment]
I can't reproduce this in the demos.

![Image](https://github.com/user-attachments/assets/d88486e2-9bb2-4fc1-9675-b13600e4bf78)

But the placeholder color itself seems to be wrong for every `FluentSelect` regardless if it's being used in a dialog or not. When no value is selected and a placeholder is provided, the web components will add this inline CSS:
```css
#ID::part(selected-value) {
	white-space: nowrap;
	color: var(--neutral-base-color);
}
```

Which is using the wrong CSS variable. Instead it should use `--input-placeholder-rest`

There is a simple workaround for this by adding this line of CSS:
```razor
fluent-select[current-value=""]::part(selected-value) {
  color: var(--input-placeholder-rest) !important;
}
```

I could create a PR for this but I'm always hesitating with providing CSS which uses `!important` in case the user may want to override it. But I think it may be required since the CSS selector from the web components is pretty specific.

@vnbaaij @dvoituron let me know what you think.

**Comment by MarvinKlein1508** [comment]
With this change it looks like this.

Before:
![Image](https://github.com/user-attachments/assets/e80f4bb5-894b-4247-a0a9-e8241e2e0146)

After:
![Image](https://github.com/user-attachments/assets/2581c984-71a3-4005-9a0d-4e157d7739b4)

**Comment by vnbaaij** [comment]
Is the wrong selector one that we specify anywhere? Or does it come from the web component?

If the first, then we just need to fix it on our side. If the second, then I think we can add our own specific css including the !important

**Comment by MarvinKlein1508** [comment]
@vnbaaij as far as I can tell it is coming directly from the web components. But it would be great if you can double check. Perhaps I'm overseeing anything.

**Comment by vnbaaij** [comment]
I think it is us...

https://github.com/microsoft/fluentui-blazor/blob/dev/src%2FCore%2FComponents%2FList%2FFluentSelect.razor.cs#L25-L27

**Comment by JamesNK** [comment]
That style is added when SelectedOption is null. I wonder if the way I’ve specified the select causes SelectedOption to stay null. The bind value is definitely updating the model bound to the selected.

**Comment by MarvinKlein1508** [comment]
@JamesNK yes. in the demos it is working fine. So it must be something on your end. I've put a select into one dialog:

![Image](https://github.com/user-attachments/assets/4d588c8d-2651-4059-88c6-d94ca3a6c6dd)

**Comment by JamesNK** [comment]
This is how I added this select:

```razor
<FluentSelect TOption="System.String"
              @bind-Value="localItem.Value"
              Label="@localItem.Label"
              Placeholder="@localItem.Placeholder"
              Required="localItem.Required"
              Height="300px">
    @foreach (var option in localItem.Options)
    {
        <FluentOption Value="@option.Key">@option.Value</FluentOption>
    }
</FluentSelect>
```

The value is successfully bound to, but I'm guessing `SelectedOption` stays null so the placeholder style is always applied.

**Comment by JamesNK** [comment]
I changed it to bind to options and now the placeholder doesn't get the style because `KeyValuePair<string, string>` is a struct and so `SelectedOption` can never be null. I don't think checking for null on `SelectedOption` is a good pattern for deciding whether there is a value or not.

```razor
<FluentSelect TOption="KeyValuePair<string, string>"
              @bind-Value="localItem.Value"
              Label="@localItem.Label"
              Placeholder="@localItem.Placeholder"
              Required="localItem.Required"
              Items="localItem.Options"
              OptionValue="@(kvp => kvp.Key)"
              OptionText="@(kvp => kvp.Value)"
              Height="300px" />
```

**Comment by JamesNK** [comment]
I got it working by changing the option type to a class:

```razor
<FluentSelect TOption="SelectViewModel<string>"
              @bind-Value="localItem.Value"
              Label="@localItem.Label"
              Placeholder="@localItem.Placeholder"
              Required="localItem.Required"
              Items="localItem.Options.Select(o => new SelectViewModel<string> { Id = o.Key, Name = o.Value })"
              OptionValue="@(kvp => kvp.Id)"
              OptionText="@(kvp => kvp.Name)"
              Height="300px" />
```

It correctly has a grayed out placeholder and white text for a selected value.

**Comment by MarvinKlein1508** [comment]
@JamesNK yea using null and checking for null is quite strange in this components. When you don't provide an `Items` parameter you have to take care of the binding yourself. This is how I have done it within my apps.
```razor
<FluentSelect TOption="Hauptbereich" Label="Hauptbereich" Width="100%;">
    <FluentOption Value="null" Selected="@(Input.HauptbereichId is null)" OnSelect="(val) => Input.HauptbereichId = null">--- Auswählen ---</FluentOption>
    @foreach (var item in Storage.Get<Hauptbereich>())
    {
        <FluentOption TOption="Hauptbereich" Value="@item.HauptbereichId.ToString()" Selected="@(Input.HauptbereichId == item.HauptbereichId)" OnSelect="(val) => Input.HauptbereichId = item.HauptbereichId">@item.Name</FluentOption>
    }
</FluentSelect>
```

A lot of overhead. When you do it with vanilla blazor and html this shrinks down to:
```razor
<InputSelect @bind-Value="Input.HauptbereichId">
    <option value="">--- SELECT ---</option>
    @foreach (var item in Storage.Get<Hauptbereich>())
    {
        <option value="@item.HauptbereichId.ToString()">@item.Name</option>
    }
</InputSelect>
```

The downside of this is that you cannot bind to complex objects, which you can in `FluentSelect`. But if you only need bare functionality you can mimic the FluentUI select with this CSS class:
```css
.fluent-select {
    background: padding-box linear-gradient(var(--neutral-fill-rest),var(--neutral-fill-rest)),border-box var(--neutral-stroke-control-rest);
    border: calc(var(--stroke-width) * 1px) solid transparent;
    border-radius: calc(var(--control-corner-radius) * 1px);
    height: calc((var(--base-height-multiplier) + var(--density)) * var(--design-unit) * 1px);
    align-items: center;
    box-sizing: border-box;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: initial;
    font-variation-settings: var(--type-ramp-base-font-variations);
    /*min-height: 100%;*/
    padding: 0 calc(var(--design-unit) * 2.25px);
    color: var(--neutral-foreground-rest);
    fill: currentcolor;
    font-family: var(--body-font);
}

.fluent-input-label {
    margin-bottom: calc(var(--design-unit) * 1px);
}
```
