### ISSUE TITLE
feat: add option to focus buttons in dialog

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#3954]
# 🙋 Feature Request

I couldn't find a way to focus the primary/secondary buttons in the dialog footer when the dialog opens.

## 🤔 Expected Behavior

For example, focusing a button on a confirmation dialog is a common UI pattern. There would be a way to focus one of them when the dialog/message box/confirmation opens.

## 💁 Possible Solution

Add `FocusPrimaryButton` and `FocusSecondaryButton` to dialog parameters?

**Comment by vnbaaij** [comment]
To set focus, `FluentButton` exposes the `AutoFocus` parameter. This can currently not be set through the `FluentDialogFooter` and we don't intent to add that in the near future as the component will undergo changes for v5.

What you _can_ do is just specify your own footer. See https://github.com/microsoft/fluentui-blazor/blob/1a15f321e03838d287fe46accf3cd6daaf6a6a8a/examples/Demo/Shared/Pages/Dialog/Examples/SimpleCustomizedDialog.razor?plain=1 for an example. When doing that you can then use `AutoFocus`. 

You'll need to add the following style as currently the `fluent-button` web component does not apply the `:focus-visible` pseudo selector when receiving focus:

```css
fluent-button::part(control):focus {
    outline: calc(var(--focus-stroke-width) * 1px) solid var(--focus-stroke-outer);
    box-shadow: 0 0 0 calc(var(--focus-stroke-width) * 1px) var(--focus-stroke-inner) inset !important;
    outline-offset: calc(var(--focus-stroke-width) * -1px);
}
```
