### ISSUE TITLE
fix: FluentSelect inside overflow:auto container

### ISSUE THREAD

**Issue by JamesNK** [microsoft/fluentui-blazor#3960]
# 🐛 Bug Report

I have a dialog that I've given a max height to. The dialog could contain a FluentSelect instance and the dialog body has a max height and scrolls when the height is exceeded:

```css
#interactions-input-dialog .interaction-input-dialog {
    max-height: 50vh;
    overflow-y: auto;
}
```

When the FluentSelect opens, it opens inside the scrollable container, adding scrollbars and not being completely visible:

![Image](https://github.com/user-attachments/assets/f4920680-76e2-4d2b-a376-310a5b68cb6b)

## 🤔 Expected Behavior

I expect the FluentSelect to behave like a normal HTML select and open outside the scrollable element:

![Image](https://github.com/user-attachments/assets/21c95f75-042d-4e62-a174-0ad6a0b1cc5a)

## 😯 Current Behavior

Opens inside the scrollable container, adding scrollbars and not being completely visible.

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and Fluent UI Blazor library Version [e.g. 8.0.2 and 4.4.1]

**Comment by JamesNK** [comment]
How it should look (before changes to add a max height + overflow):

![Image](https://github.com/user-attachments/assets/e3ec4686-9b75-4c82-b601-a70eaa11a97e)

**Comment by vnbaaij** [comment]
If I just add a Select to one of our Dialog examples, it works as expected:

![Image](https://github.com/user-attachments/assets/137b03b7-d010-45a2-97fa-e84ec1a297aa)

I actually can't get it to behave like what you have, even after adding the styles you used in your first post.

Are you sure you are setting the styles on the `fluent-dialog`-element?

We need a working, ready-to-run reproduction sample if you want us to investigate further.

**Comment by WenLiHou** [comment]
```
<div style="overflow-y:auto; display:flex;">
     <div style="width:100%; height:200px; background-color:lightgray;">
<FluentSelect TOption="string"      
              Height="300px">
              </FluentSelect>
     </div>
 </div>
```  
you can try like this to reproduction... I am also troubled by this issue.

**Comment by vnbaaij** [comment]
@WenLiHou not really clear what you want us to do with that code

**Comment by JamesNK** [comment]
> If I just add a Select to one of our Dialog examples, it works as expected:
> 
> ![Image](https://github.com/user-attachments/assets/137b03b7-d010-45a2-97fa-e84ec1a297aa)
> 
> I actually can't get it to behave like what you have, even after adding the styles you used in your first post.
> 
> Are you sure you are setting the styles on the `fluent-dialog`-element?
> 
> We need a working, ready-to-run reproduction sample if you want us to investigate further.

Did your dialog have `overflow-y: auto;`? Adding overflow and max height is what caused the issue.

**Comment by JamesNK** [comment]
https://github.com/JamesNK/fluentui-blazor/commit/d366979dc54f6d08391e482f8539e008faa1e074

![Image](https://github.com/user-attachments/assets/b5bd36f5-ed42-4e48-8205-a4afcef00082)

Reopen please. I don't have permission.

**Comment by WenLiHou** [comment]
‌I tried using DeepSeek to find a solution, and I've found one.

```  
/* 强制下拉框突破容器限制 */
  fluent-select::part(listbox) {
      position: absolute !important;
      z-index: 1000 !important;
      max-height: 200px;
      overflow-y: auto;
  }

  /* 修正滚动容器行为 */
  .scroll-container {
  }

  /* 临时解除滚动裁剪 */
  .scroll-container:has(fluent-select[open]) {
      overflow: visible !important;
  } ```

**Comment by vnbaaij** [comment]
I'm sorry, but I can't get it to work. @WenLiHou please post a complete working solution if you have one. Short blubs of code do not help here

**Comment by JamesNK** [comment]
I included a link to a commit that repos the issue

**Comment by vnbaaij** [comment]
@JamesNK Yes, I saw your link and I am able to reproduce it with that code. Thanks. 
Just don't know how to solve it/prevent it from happening...

**Comment by JamesNK** [comment]
I think the popup part needs to be displayed by something outside of the container. I think that's what already happens with other popup type controls using providers.

**Comment by vnbaaij** [comment]
In this case the listbox (the popup part) is controlled by the web component. We don't have a posibillity to intervene there

**Comment by dvoituron** [comment]
The next web components use the new HTML `dialog` element to avoid this issue.

**Comment by MarvinKlein1508** [comment]
I've tried to give this one a shot but I couldn't figure out a fix for it. 

In case you wanna debug this issue make sure to use Google Chrome and then hit `CTRL+SHIFT+P` in the dev tools and enable `Emulate a focused page`. This way you can manipulate the DOM without the menu closing itself automatically.

<img width="632" height="269" alt="Image" src="https://github.com/user-attachments/assets/fe4e82c2-fa50-4b7f-a4a7-eac0f7e4aed7" />

The only thing I figured out was when you set the `position` of the listbox to `fixed` then it's floating above the dialog but in the wrong size and position.

**Comment by MarvinKlein1508** [comment]
The solution from @WenLiHou is not a really good one. This one just changes the overflow behaviour to automatically show all overflow when your div contains an opened `fluent-select`. At least it broke the provided demo from @JamesNK in my case.

**Comment by MarvinKlein1508** [comment]
@JamesNK  In case this might be helpful for you:

I have some controls which I want to use the native html `select` tags in order for them to take advantage of the select UI on mobile devices. I actually don't care about the `fluent-select` dropdown at all. So I mimic the UI with this CSS class.
```css
.fluent-select {
    background: padding-box linear-gradient(var(--neutral-fill-rest),var(--neutral-fill-rest)),border-box var(--neutral-stroke-control-rest);
    border: calc(var(--stroke-width) * 1px) solid transparent;
    border-radius: calc(var(--control-corner-radius) * 1px);
    height: calc((var(--base-height-multiplier) + var(--density)) * var(--design-unit) * 1px);
    align-items: center;
    box-sizing: border-box;
    font-family: var(--body-font);
    font-size: var(--type-ramp-base-font-size);
    line-height: var(--type-ramp-base-line-height);
    font-weight: initial;
    font-variation-settings: var(--type-ramp-base-font-variations);
    /*min-height: 100%;*/
    padding: 0 calc(var(--design-unit) * 2.25px);
    color: var(--neutral-foreground-rest);
    fill: currentcolor;
    font-family: var(--body-font);
}
```

This will render like this:
![Image](https://github.com/user-attachments/assets/68f137c9-6927-4be6-909e-ef5fcf693f3b)

In case of your provided demo you might need to tweak the code a bit to work properly.
