### ISSUE TITLE
MenuButton should not expand the parent

### ISSUE THREAD

**Issue by mrpmorris** [microsoft/fluentui-blazor#456]
I have a MenuButton in a toolbar at the top of my page.  When I open the menu, the toolbar grows.

I made the following changes....

```html
<div class="container">
  <!-- added container class -->
</div>
```

```css
.container {
    position: relative;
}

::deep > fluent-button + fluent-menu {
    display: none;
}

::deep > fluent-menu.visible {
    display: block;
    position: absolute;
    width: fit-content;
}
```
