### ISSUE TITLE
docs: fix FluentBadge custom css

### ISSUE THREAD

**Issue by cliedeman** [microsoft/fluentui-blazor#734]
# 🙋 Documentation Request

https://www.fluentui-blazor.net/Badge
the scoped css sample does not work

```
::deep > fluent-badge {
    --badge-fill-highlight: #ffd800;
    --badge-fill-lowlight: #c8c6c4;
    --badge-color-highlight: #000;
    --badge-color-lowlight: #fff;
}
```

in the browser tools I see the warning that the css variable is not found

## 💁 Possible Solution

Remove the scoped version and use the global version in the docs?

```
fluent-badge {
    --badge-fill-highlight: #ffd800;
    --badge-fill-lowlight: #333;
    --badge-color-highlight: #000;
    --badge-color-lowlight: #fff;
}
```

I am new to blazor and fast so I am unsure if the scoped css variables should work at all

**Comment by vnbaaij** [comment]
Hi,

And welcome to Blazor, Fluent UI and Fast. Sometimes the browser tools gets it wrong. It shows a var as grayed out but it actually is found and works. Think that is the case here as well. This is what I see in Edge Canary:

<img width="746" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/1761079/13a2c4e3-23f3-4375-a2b0-a943e422e23c">
The yellow marked id is what Blazor uses to scope the variables.  You can see the ::deep has been replaced with that id in the right side of the image.

**Comment by cliedeman** [comment]
It doesn't work in edge canary for me either

<img width="1272" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/3578740/2bfcbbf8-c305-41a8-89e2-3f00f04fb36e">

<img width="400" alt="image" src="https://github.com/microsoft/fluentui-blazor/assets/3578740/331e5ba2-29b4-4476-8fc4-a26799ed5a29">

**Comment by vnbaaij** [comment]
Ok, let's take a step back. What are you trying to achieve? And does setting `BackgroundColor` and `Color` not work (see https://www.fluentui-blazor.net/Badge#appearances)?

**Comment by cliedeman** [comment]
I'll create a sample repro and get back to you

**Comment by cliedeman** [comment]
hi @vnbaaij 

I found the issue.

I had to change 

```css
::deep > fluent-badge {
    --badge-fill-highlight: #ffd800;
    --badge-fill-lowlight: #c8c6c4;
    --badge-color-highlight: #000;
    --badge-color-lowlight: #fff;
}
```

to 

```css
::deep fluent-badge {
    --badge-fill-highlight: #ffd800;
    --badge-fill-lowlight: #c8c6c4;
    --badge-color-highlight: #000;
    --badge-color-lowlight: #fff;
}
```

Thanks
